
/*
 * InterfacePanel4.java
 *
 * Created on 2009-05-05, 11:08:58
 */

package Interface;

import Algorithm.Solver;
import java.io.*;


public class InterfacePanel4 extends javax.swing.JFrame {

    
    private Integer[][] koszty;

    private static final int INF=100000000;


    int ilosc;


    private int tryb;


    Solver rozw;


    int iteracje;


    int ktoraIteracja = 0;

    /** Creates new form InterfacePanel4 */
    public InterfacePanel4(int t) {
        initComponents();
        tryb = t;
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFileChooser1.setControlButtonsAreShown(false);
        jFileChooser1.setCurrentDirectory(null);
        jFileChooser1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Charger un fichier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 15))); // NOI18N

        jButton1.setText("plus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void saveCosts()
    {
        try
        {
        FileWriter fw=new FileWriter("wynik.txt");
        fw.write("Pour une matrice de coût donné:\r\n\r\n");
        for(int i=0; i<ilosc; ++i)
        {
            String linia=new String();
            for(int j=0; j<ilosc; ++j)
            {
                if(koszty[i][j]!=100000000)
                 linia+=koszty[i][j];
                else
                    linia+="inf";
                linia+=" ";
            }
            linia+="\r\n";
            fw.write(linia);

        }
        fw.write("\r\n");
        fw.write("Le plus court chemin est:\r\n\r\n");
        String sciezka=rozw.printAnswer2();
        fw.write(sciezka);

        fw.close();
        }catch(IOException e){System.out.println("vous ne pouvez pas écrire sur disque");}
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int m1, m2, k;
        String linia;
        File plik = jFileChooser1.getSelectedFile();
        try
        {
             BufferedReader input =  new BufferedReader(new FileReader(plik));
             ilosc = Integer.parseInt(input.readLine());
             koszty = new Integer[ilosc][];
             for (int i = 0; i<ilosc; i++)
             {
                koszty[i] = new Integer[ilosc];
             }

            /* for(int j = 0; j < ilosc*(ilosc-1); j++)
             {
                 linia = input.readLine();
                 String[] liczby = linia.split(" ");
                 m1 = Integer.parseInt(liczby[0]);
                 m2 = Integer.parseInt(liczby[1]);
                 k = Integer.parseInt(liczby[2]);

                 if (spr_miasta(m1, m2))
                    koszty[m1-1][m2-1] = k;

             }*/
                         //DD
                         for(int j=0; j<ilosc; ++j)
             {
                 linia=input.readLine();
                 String[]liczby=linia.split(" ");
                 Integer wagi[]=new Integer[ilosc];
                 for(int p=0; p<ilosc; ++p)
                 {
                     wagi[p]=Integer.parseInt(liczby[p]);
                         if(spr_miasta(j+1,p+1))
                     koszty[j][p]=wagi[p];
                 }

             }
             for(int i=0; i<ilosc; ++i)
             {
                 koszty[i][i]=INF;
             }

        }
    catch (IOException ex)
        {
        }
        
    try {
            InterfacePanel6 Panel6 = new InterfacePanel6(tryb, ilosc, koszty);
            Panel6.setVisible(true);
        }
    catch (IOException iOException)
        {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

private boolean spr_miasta (int a, int b)
{
    if ((a <= ilosc)&&(b <= ilosc)&&(a != b))
        return true;
    return false;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables

}